spring:
  redis:
    jedis:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
    port: 6379
    host: 127.0.0.1
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.10.182:3306/ONPMS?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    username: onpms
    password: onandon12#
    hikari:
      connection-init-sql: select * from MBER
  jpa:
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
    open-in-view: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
logging:
  level:
    kr:
      co:
        kr:
          co:
            onandon:
              onpms: debug
    org:
      hibernate:
        type:
          descriptor:
            sql: trace
